nmHoistingLimits: workspaces

nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: 'https://registry.npmjs.org'

catalog:
  es-toolkit: 1.43.0
  typescript: 5.9.3
  vitest: 4.0.16
  tsdown: 0.18.1

catalogs:
  rolldown:
    "@rolldown/pluginutils": 1.0.0-beta.55
    rolldown: 1.0.0-beta.55
