catalog:
  es-toolkit: 1.43.0
  tsdown: 0.18.1
  typescript: 5.9.3
  vitest: 4.0.16

catalogs:
  rolldown:
    "@rolldown/pluginutils": 1.0.0-beta.58
    rolldown: 1.0.0-beta.58

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistries:
  "https://registry.npmjs.org":
    npmAlwaysAuth: true
