catalog:
  es-toolkit: 1.43.0
  tsdown: 0.20.0-beta.1
  typescript: 5.9.3
  vitest: 4.0.17

catalogs:
  rolldown:
    '@rollipop/rolldown': 1.0.0-rc.2
    '@rollipop/rolldown-pluginutils': 1.0.0-rc.2

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: 'https://registry.npmjs.org'

npmRegistries:
  'https://registry.npmjs.org':
    npmAlwaysAuth: true
