catalog:
  tsdown: 0.21.5
  typescript: 5.9.3
  vitest: 4.1.1

catalogs:
  rolldown:
    '@rollipop/rolldown': 1.0.0-rc.6
    '@rollipop/rolldown-pluginutils': 1.0.0-rc.6

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: 'https://registry.npmjs.org'

npmRegistries:
  'https://registry.npmjs.org':
    npmAlwaysAuth: true
